# -*- coding: utf-8 -*-
"""Paraphrase .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VN1CkkNcIUEVcYEV8Bwk-FC48ybGNdJp
"""

from sentence_transformers import SentenceTransformer, util
from sentence_transformers.util import paraphrase_mining

model = SentenceTransformer("all-MiniLM-L6-v2")

sentences = [
    "The cat sits outside",
    "A man is playing guitar",
    "I love pasta",
    "The new movie is awesome",
    "The cat plays in the garden",
    "A woman watches TV",
    "The new movie is so great",
    "Do you like pizza?",
    "She enjoys reading books",
    "He is walking his dog",
    "The weather is nice today",
    "Let's go to the beach",
    "I need a cup of coffee",
    "They are planning a trip",
    "She cooks delicious meals",
    "I am learning to play the piano",
    "He works at a tech company",
    "This book is very interesting",
    "The sun is shining brightly",
    "It's raining outside",
    "The children are playing soccer",
    "He is fixing the car",
    "She writes beautiful poetry",
    "The flowers are blooming",
    "I enjoy hiking in the mountains",
    "He is swimming in the pool",
    "We are watching a comedy show",
    "The dog is barking loudly",
    "She is painting a landscape",
    "He likes to play video games",
    "I am studying for my exams",
    "They are building a new house",
    "The coffee shop is busy",
    "He listens to classical music",
    "She is designing a website",
    "I bought a new laptop",
    "They are baking cookies",
    "The bird sings in the morning",
    "He loves going to concerts",
    "She practices yoga every day",
    "The phone is ringing",
    "I need to finish this project",
    "The restaurant has great food",
    "He collects rare coins",
    "She enjoys watching documentaries",
    "They are exploring the city",
    "The laptop is charging",
    "He is training for a marathon",
    "I meditate every morning",
    "The bakery sells fresh bread",
    "She is learning French"
]

s1 = "The cat sits outside"
s2 = "A man is playing guitar"
s3 = "I love pasta"
s4 = "The new movie is awesome"
s5 = "The cat plays in the garden"

embeddings = model.encode(sentences, convert_to_tensor=True)

print("Embedding shape:", embeddings.shape)

paraphrase = paraphrase_mining(model, sentences)
paraphrase[:20]

for i in paraphrase[:20]:
  score,i,j = i
  print("{}\t\t\t\t{}\t\t\t\tscore : {:.4f}".format(sentences[i],sentences[j],score))

model = SentenceTransformer("distiluse-base-multilingual-cased-v1")

corpos1 = ["The cat sits outside",
"A man is playing guitar",
"I love pasta",
"The new movie is awesome",
"The cat plays in the garden"]

corpos_emb = model.encode(corpos1, convert_to_tensor=True)

cosine_similarity = util.pytorch_cos_sim(corpos_emb, corpos_emb)
avg_sim = cosine_similarity.mean(dim=1)
outlier_index = avg_sim.argmin().item()
outlier_index
print(f"Outlier sentence: {corpos1[outlier_index]}(avg similarity : {avg_sim[outlier_index]})")

corpos2 = [" She enjoys reading books",
"He is walking his dog",
"The weather is nice today",
"Let's go to the beach",
"I need a cup of coffee",
"They are planning a trip"]
corpos_emb = model.encode(corpos2, convert_to_tensor=True)

cosine_similarity = util.pytorch_cos_sim(corpos_emb, corpos_emb)
avg_sim = cosine_similarity.mean(dim=1)
outlier_index = avg_sim.argmin().item()
outlier_index
print(f"Outlier sentence: {corpos2[outlier_index]}(avg similarity : {avg_sim[outlier_index]})")

corpos3 = ["I love pasta",
"The new movie is awesome",
"The cat plays in the garden",
"A woman watches TV",
"The new movie is so great",
"Do you like pizza?"]

corpos3_emb = model.encode(corpos3, convert_to_tensor=True)

cosine_similarity = util.pytorch_cos_sim(corpos_emb, corpos_emb)
avg_sim = cosine_similarity.mean(dim=1)
outlier_index = avg_sim.argmin().item()
outlier_index
print(f"Outlier sentence: {corpos3[outlier_index]}(avg similarity : {avg_sim[outlier_index]})")

corpos4 = ["The cat sits outside",
"A man is playing guitar",
"I love pasta",
"The new movie is awesome",
"The cat plays in the garden",
"A woman watches TV",
"The new movie is so great",
"Do you like pizza?"]
corpas4_emb = model.encode(corpos4, convert_to_tensor=True)

cosine_similarity = util.pytorch_cos_sim(corpos_emb, corpos_emb)
avg_sim = cosine_similarity.mean(dim=1)
outlier_index = avg_sim.argmin().item()
outlier_index
print(f"Outlier sentence: {corpos4[outlier_index]}(avg similarity : {avg_sim[outlier_index]})")

